### ISSUE TITLE
No. of Titles on Catalog, Category and Series pages

### ISSUE THREAD

**Issue by bozana** [UB-Heidelberg/omp#12]
Could this be somehow differently classified/identified instead of using `<h2 class="page_subtitle">` -- to be able to hide it, if wished?

**Comment by bozana** [comment]
This looks now much better :-)

**Comment by NateWr** [comment]
:thumbsup:

**Comment by asmecher** [comment]
@bozana, does this mean Nate's already tackled it? Or does it still need a markup change?
