### ISSUE TITLE
Custom Blocks

### ISSUE THREAD

**Issue by bozana** [UB-Heidelberg/omp#13]
Could the custom blocks be at the same position i.e. have the same layout as Browse, Language, Information block?

**Comment by NateWr** [comment]
They should be now. See [this commit](https://github.com/pkp/customBlockManager/commit/c67c4746dd8e7bbbde6919c7c8e6b762870a23f8). Here's an example of what one looks like:

![custom-block](https://cloud.githubusercontent.com/assets/2306629/11059033/060223a4-878f-11e5-8aa3-f520f59e6c1c.png)

There are [a bunch of block plugins](https://github.com/pkp/customBlockManager/pull/6#issuecomment-154204306) that need their templates updated to match the new block HTML pattern:

```
<div class="pkp_block block_[type]">
  <!-- optional title -->
  <span class="title">Title</span>
  <!-- required content wrapper -->
  <div class="content">
    Any content
  </div>
</div>
```

**Comment by asmecher** [comment]
@bozana, can you check and close this one if it's OK?

**Comment by bozana** [comment]
Great! Thanks!
