### ISSUE TITLE
Right Sidebar

### ISSUE THREAD

**Issue by bozana** [UB-Heidelberg/omp#14]
Is the right sidebar still meant to be used (e.g. if I move the blocks in settings > website > appaearance > sidebar management to the right column) i.e. should the default theme consider it?

**Comment by asmecher** [comment]
We're considering removing support for this.

**Comment by asmecher** [comment]
If you want to keep the right sidebar, speak now or forever hold your peace ;)

**Comment by bozana** [comment]
Hmmm... I cannot foresee things yet, so lets say I will hold my peace for now ;-)

**Comment by asmecher** [comment]
The right sidebar has been removed; can this be closed?
