### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bozana** [UB-Heidelberg/omp#15]
What would be the right way for a press to change/design the home page (elements, structure, content)?

**Comment by asmecher** [comment]
For a single press site, or multiple press site?

**Comment by bozana** [comment]
Both :-) But above all single press site :-)

**Comment by asmecher** [comment]
For a single press site, the "site-wide" aspects are hidden, and you can just work with the press setup area. When there are multiple presses, then there will be a separate "site settings" area. (Single-press installs were finding it confusing that they had to consider both site-wide and journal-specific areas, so we collapsed them together in that case.)

**Comment by bozana** [comment]
I mean: if I enter something either into the settings > press > press homepage or settings > website > appearance > additional content I don't see it on the home page i.e. I cannot change the content of the home page at the moment, right?

**Comment by asmecher** [comment]
If you only have a single press, the site-wide homepage shouldn't exist -- you should always be redirected to the press-specific homepage. Are you seeing something else?

**Comment by bozana** [comment]
No, that's true -- I am always redirected to the press home page. But I cannot add any content (text, images,...) to the press home page.

**Comment by asmecher** [comment]
Ah, I think this is probably due to the "additional content" field not presenting in the homepage. @NateWr, probably just a missing variable in the front-end templates.

**Comment by NateWr** [comment]
Nothing's there at the moment and we're re-evaluating many of the options in the backend. I suspect we'll have a series of components with on/off toggles, and one tinymce field for additional content. But none of this is set up at the moment.

**Comment by bozana** [comment]
OK, that answers the question i.e. how is it planed to be... :-) THANKS!

**Comment by asmecher** [comment]
Can this be closed?
