### ISSUE TITLE
Select books for carousel not working

### ISSUE THREAD

**Issue by CFanselow** [UB-Heidelberg/omp#17]
Clicking on "Feature" doesn't do anything.

**Comment by asmecher** [comment]
We're discussing whether or not to keep the "featured" designation. @CFanselow, maybe you could describe the way you're using it so @NateWr can consider in the front end design?

**Comment by CFanselow** [comment]
http://langsci-press.org/
But we consider removing it.

**Comment by asmecher** [comment]
We've decided to remove the carousel, so I'm happy to hear you're considering the same. The issue for resolving the problems with the "feature" flag is here:
https://github.com/pkp/pkp-lib/issues/986

**Comment by CFanselow** [comment]
okay, thanks for the information!
