### ISSUE TITLE
Upload submission file: 'Invalid file ids' error, if a submission file with a similar name is not a revision

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#18]
If I upload two submission files with similar names (e.g. book.epub and book.pdf), after uploading the second one the "Possible Duplication or Revision Detected" notification is displayed. If I select "Select file (to preserve history)." and continue, the submission file wizard doesn't advance. From the error log:

```
omp: Invalid file ids!
```

However, the file is still inserted in the database.

**Comment by asmecher** [comment]
Thanks -- I've fixed this in OMP master. You'll need to update both OMP and pkp-lib.

**Comment by kadowa** [comment]
Looks good, thanks!

**Comment by kadowa** [comment]
I just noticed that the buttons below the file (Edit metadata/Delete) are gone after I pulled – I updated both omp and pkp-lib. The error log shows nothing. Do you have an idea what went wrong, @asmecher?

![files](https://cloud.githubusercontent.com/assets/8066366/11815513/54394d12-a34c-11e5-8adc-a9d71f89d7d3.png)

**Comment by asmecher** [comment]
@kadowa, try clearing all cache files -- particularly `cache/*.css` -- to see if that helps. I suspect that's unrelated to this issue.

**Comment by kadowa** [comment]
That was it – thanks!
