### ISSUE TITLE
publication format links/status

### ISSUE THREAD

**Issue by CFanselow** [UB-Heidelberg/omp#19]
In the old version, these items also carried information about the status. Now the first two seem redundant to me and if so it would be better to make the page more slender. For the third one ("available") the naming is confusing for me. Shouldn't it rather be "change availability"? 

![statuslinks](https://cloud.githubusercontent.com/assets/7779279/10761573/4ee7deb0-7cc2-11e5-8aac-6607fc9955a4.png)

**Comment by asmecher** [comment]
Check out the current master branch (both omp and lib-pkp), and `rm cache/*.css` to clear the cached CSS file.

**Comment by CFanselow** [comment]
Great!
