### ISSUE TITLE
Empty expedite modal

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#20]
![expedite](https://cloud.githubusercontent.com/assets/8066366/10761920/dfbc9420-7cc3-11e5-9bd7-9fe82834da7b.png)

The functionality seems intact though: publication format and page proof for the PDF are created.

**Comment by asmecher** [comment]
@withanage, I've added a commit that should fix this.

**Comment by kadowa** [comment]
Fixed, thanks.

**Comment by withanage** [comment]
thanks alex. is confirmed.
