### ISSUE TITLE
user is lost

### ISSUE THREAD

**Issue by CFanselow** [UB-Heidelberg/omp#21]
I have created a new user and maybe didn't save the form correctly. The user is written to the db but it doesn't show up in "users & roles".

**Comment by asmecher** [comment]
User creation is a two-step process: first the user account is created, then they're given roles. If you stop after the first step, the account will be created without roles.

To work with that account (including giving it roles), click the magnifying glass to the top right of the user list and check the box labelled "Include users with no roles in this press".
