### ISSUE TITLE
Public Identifier Plugins 

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/omp#22]
Custom settings for urn and doi plugin fails.
![plugin](https://cloud.githubusercontent.com/assets/1921992/10817671/bc678d30-7e3b-11e5-8fef-d429d51fe4ba.png)
@asmecher
Can it be that the  plugin structure basically changed after
https://github.com/pkp/pkp-lib/commit/e678078cf1717bd9785b446f84037eeda969fa9d
and modifications are needed in the plugin-level.

Confirmation
1 Static page plugin  has this kind of options and work as intented.

**Comment by asmecher** [comment]
Thanks, @withanage, I'll take a look.
@bozana, I know you'll be working on this stuff shortly, but this is my bug so I'll fix it :)

**Comment by asmecher** [comment]
I've committed fixes to both OJS and OMP master branches to get the settings forms working. By the way, was this OJS you were testing, or OMP? The OMP master branch doesn't have a URN plugin.

**Comment by kadowa** [comment]
OMP -- I've implemented a [URN DNB](https://github.com/UB-Heidelberg/urn_dnb) plugin for OMP (similar to the one by @bozana for OJS). I borrowed a lot of code from the DOI plugin, so I can probably apply the same fixes. Thanks for the quick reply!

**Comment by withanage** [comment]
Thanks a lot  for fixing it. looks good.
