### ISSUE TITLE
Generic Plugins

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#24]
From #8: For some of the generic plugins, management options are available, but don't work (Translator, Usage Statistics).

![generic](https://cloud.githubusercontent.com/assets/8066366/10818108/3991b7ce-7e3f-11e5-841e-f13b9705ce1e.png)

![usage_statistics](https://cloud.githubusercontent.com/assets/8066366/10818109/3be9c73c-7e3f-11e5-8f52-6db413de47f6.png)

Might also be connected to the changes in plugin management here https://github.com/pkp/pkp-lib/commit/e678078cf1717bd9785b446f84037eeda969fa9d?

**Comment by asmecher** [comment]
I've committed some corrections to the usage stats plugin's use of the plugin API (associated with pkp/pkp-lib#700). The translation plugin worked fine here, though -- perhaps we had an out-of-date submodule hash for that plugin. Could you...

```
cd plugins/generic/translate
git pull
```

...to update it, and if it's still not working, report what's happening when you click the Translate link?

**Comment by kadowa** [comment]
Both working now, thanks!
