### ISSUE TITLE
DOI plugin settings form (OMP)

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#25]
Following up on #22: the DOI plugin settings form is now accessible, but cannot be saved. Error log: `omp: 404 Not Found`

Form validation seems to be broken somehow, too. If I select "Use default patterns." I still get an alert for the custom pattern field, when I click "Save".

![doi_settings](https://cloud.githubusercontent.com/assets/8066366/10843154/76ff5568-7ef7-11e5-8d28-d4742c21d9e4.png)

@asmecher, could you have another look?

**Comment by asmecher** [comment]
@kadowa, this should be fixed -- try again?

**Comment by kadowa** [comment]
Fixed, thanks!
