### ISSUE TITLE
DOI plugin: Reassign DOIs

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#27]
Sorry, there is one more issue with the DOI plugin @asmecher. Like the settings form (#25), the "Reassign DOIs" form does nothing after I click on "Ok". Changing https://github.com/pkp/omp/blob/master/plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php#L76 to this

``` php
    $request->url(null, null, 'manage', null, array('verb' => 'settings', 'clearPubIds' => true, 'plugin' => $plugin->getName(), 'category' => 'pubIds'))
```

fixes it for me.

**Comment by asmecher** [comment]
Committed, thanks!
