### ISSUE TITLE
Error display when deleting an author from the list of contributors

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#28]
Autor löschen verursacht eine Fehlermeldung (translation below)

![bildschirmfoto vom 2015-11-11 09 44 13](https://cloud.githubusercontent.com/assets/8066366/11087210/c98f5d40-8858-11e5-8392-3ceb59581b18.png)

**Comment by asmecher** [comment]
If it's feasible, can you work with the system in English? It's going to be hard (but not impossible) for me to figure out what part of the interface you're working with.

**Comment by kadowa** [comment]
Sorry, meant to translate this (I opened this quickly during a demonstration session) but didn't get back to it last week.

Deleting an author in the catalog tab (step 3 of the submission process) triggers an error display, when the deletion is confirmed. There is no error message in the log and after refreshing the page the selected author actually has been successfully deleted.

![delete1](https://cloud.githubusercontent.com/assets/8066366/11176648/31f8069a-8c3f-11e5-8eb8-3b8c4a6d2da5.png)
![delete2](https://cloud.githubusercontent.com/assets/8066366/11176650/3394d910-8c3f-11e5-8726-b52a00f5aa7d.png)
![delete3](https://cloud.githubusercontent.com/assets/8066366/11176651/34fc0a76-8c3f-11e5-9828-ca6b805732d4.png)

**Comment by asmecher** [comment]
@kadowa, this should be resolved with the above patch. Thanks for reporting!

**Comment by kadowa** [comment]
Resolved, thanks!
