### ISSUE TITLE
Maximum size for file upload in submission 

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#30]
The maximum file size in submission is 2 MB. This is far to little, particularly, if an author submits an entire book manuskript. The current book manuskripts submitted to heiUP are between 5 MB an 100 (!) MB large. I suggest an accepted size of 8 MB.
Of course we could split up the book into chapters before we upload the files. Though, if we want to use OMP for the submission to the advisory board, it would be better to have the whole book in one file, because it does not make sense to invest much time in splitting up the book if the book is not accepted afterwards.

**Comment by kadowa** [comment]
Changed this to 8MB on our development server – can you check, if it worked? On the productive server it's already set to 200MB.

**Comment by ankosi** [comment]
Thanks, it works!
