### ISSUE TITLE
Recipients can't be added to a new discussion

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#31]
The addition of new recipients to the discussion (in "Submission") doesn't work correctly. As soon as I click "ad user" a new field opens which is empty except a Trash. There is no way of adding a user name.

**Comment by ankosi** [comment]
![2015-11-14 11_59_39-adding_users_to_a_discussion_group](https://cloud.githubusercontent.com/assets/11088169/11163224/8b0cdda6-8ac7-11e5-847e-53beb2acf6c8.png)

**Comment by asmecher** [comment]
@AnjaKonopka, I wonder if this is because there is nobody added to the submission's Participants list. The available recipients for a discussion come from that list.

**Comment by ankosi** [comment]
@asmecher, Thanks, you are completely right. I had some participants in the press list, but they were not yet assigned to the submission. I tested again and all was fine.
