### ISSUE TITLE
New permission label is needed

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#32]
For the discussion members in Submission we need a new permission label. They should be assigned only to Submission. In our case, the the discussion members are the members of the adivsory board, so the permission label "author" doesn't put it right.

**Comment by asmecher** [comment]
Hi @AnjaKonopka -- thanks, but I'm not sure I'm following. Could you describe further, or maybe include a screenshot?

**Comment by ankosi** [comment]
Hi @asmecher; I am a little bit in delay with my answer :-)
We would like to have a user role which gives the user only access to the Submission process. This is, because a lot of publishing houses have an advisory board who decides, whether a book project will be accepted or not (before the peer review starts). The members of the board don't want to be involved in the details of the following peer review and editing process. Therefore, they should only have access to the submission stage.

**Comment by asmecher** [comment]
How about creating a new role with an "Assistant" permission role, but with an assignment only to the Submission stage? Off the top of my head, that should be enough.

**Comment by ankosi** [comment]
Good idea! I wonder how the permission role should be named? To avoid offending the advisory board members I would suggest a role name like "advisors" or - more neutrale - "discussion members" (so that they don't feel like being regarded as assitents) . "Discussion members" seems suitable to me, because the new discussion module  you added in OMP 1.2 to the submission stage seems to me the perfect module to integrate the considerations of the advisory board into the OMP Publication workflow.

**Comment by asmecher** [comment]
Just FYI, the "assistant" label won't be visible outside the Roles area of the settings. Beyond that, you can name it whatever you choose.

**Comment by ankosi** [comment]
Ok, fine!
