### ISSUE TITLE
Cover upload

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/omp#34]
Uploading an article works, but everytime we try to upload a cover it will not be saved. We tried it at this stage:
![omp_test1](https://cloud.githubusercontent.com/assets/15866252/11182190/2c1b4032-8c69-11e5-9c16-39f52b44620d.jpg)

Maybe there is a different step where the cover has to be uploaded?

@kadowa

Greetings
Daniela and Katrin Bemmann

**Comment by kadowa** [comment]
@danielawolf, das Problem in #42 habe ich noch nicht gelöst, dafür aber möglicherweise gerade dieses hier. Könntet ihr bei Gelegenheit überprüfen, ob der Cover-Upload für euch jetzt funktioniert und wenn ja, das Issue schließen?

**Comment by dastewo** [comment]
@kadowa: Danke, es klappt jetzt :-)

Zitat von kadowa notifications@github.com:
