### ISSUE TITLE
Take a view at a finished article

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/omp#35]
We tried to find a way to take a look at the published titles to change the metadata, but so far we weren't lucky. Does a way even exist?

@kadowa 

Greetings
Daniela & Katrin Bemann

**Comment by kadowa** [comment]
You can access published titles via the Dashboard, in the catalog tab (Katalog):

![dashboard_catalog](https://cloud.githubusercontent.com/assets/8066366/11209857/38ebbeac-8d24-11e5-8061-c7037d5129c8.png)

There is an issue with the layout (already reported here https://github.com/UB-Heidelberg/omp/issues/5#issuecomment-151513917) – the links for viewing and editing a title are partially hidden behind the cover thumbnails. You can still select Submission (Einreichung), which leads to the submisson page, where you can select Catalog (Katalog) to access the title's metadata.

![submission](https://cloud.githubusercontent.com/assets/8066366/11210931/156d409c-8d2c-11e5-9463-60b71de34977.png)

![catalog](https://cloud.githubusercontent.com/assets/8066366/11210966/4dcceff0-8d2c-11e5-8516-2671553fd40d.png)

@danielawolf, is this what you were looking for?

**Comment by dastewo** [comment]
@kadowa 
Yes, this looks good :-)
