### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#36]
When I check in as a pure author (without any superior permission levels), the button to submit a manuscript to the press is sticking at the right side and almost not to find.
![2015-11-18 11_05_24-greenshot_submit_a_new_manuscript](https://cloud.githubusercontent.com/assets/11088169/11238327/16d66986-8de5-11e5-90a0-7f9182a5215e.png)

**Comment by asmecher** [comment]
@NateWr, this needs a bit of a UI tweak. See also the dropdown that appears when there are multiple presses the user might submit to -- that looks even worse.

**Comment by NateWr** [comment]
Yeah it's a problem with buttons across the backend. Filed [an issue](https://github.com/pkp/pkp-lib/issues/923) so it doesn't get forgotten before OMP 1.2.

**Comment by asmecher** [comment]
@withanage, I think this should be fixed. Can you verify and close?

**Comment by ankosi** [comment]
Since I have a wider screen now, it is difficult for me to see how it has changed ...
