### ISSUE TITLE
Three text containers for catalog data instead of two

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#37]
We plan to provide a bilingual frontend Englisch/German and have implemented these two active languages for our press. I expected to see two containers for inserting the catalogue data, but now I got three???
![2015-11-18-greenshot_three_boxes_for_languages](https://cloud.githubusercontent.com/assets/11088169/11238631/39402ae6-8de7-11e5-8e0e-9f4bfa4524bc.png)

**Comment by withanage** [comment]
The test for polnish  showed the message. Removed in test server and solved.
