### ISSUE TITLE
Keys from OJS in OMP?

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#38]
There are some keys which seem to be wrong in OMP, probably herited automatically from OJS?

file: https://github.com/pkp/omp/blob/master/locale/en_US/manager.xml (OMP stable 1.1.1)

<message key="manager.setup.editorialMembers">Go to Board Members and add Editorial Board and/or Review Board members. This can be done at any point in operating the press.</message>
    <message key="manager.setup.editorialProcess1">One or more editors handle the basic steps without designated roles.</message>
    <message key="manager.setup.editorialProcess2">Managing Editor handles Submission Queue, and Table of Contents, while Section Editors handle Submission Review and Submission Editing.</message>
    <message key="manager.setup.editorialProcess3">Managing Editor handles Submission Queue, Submission Editing, and Table of Contents, while the Section Editors handle Submission Review.</message>

As far as I see OMP has no "managing editor" and no editorial board.

So as not to confuse the translators :-) it would be better to remove them

**Comment by asmecher** [comment]
Thanks, @AnjaKonopka -- those keys weren't used anywhere, so I've removed them.

**Comment by ankosi** [comment]
Great, thanks! @asmecher 
Are there more keys which never have been used? I sometimes beat my brain where a certain key ought to appear on the OMP-Website. If I know that it might appear nowhere I stop searching earlier :-)

**Comment by asmecher** [comment]
Hi @AnjaKonopka -- yes, there are definitely keys that aren't used, and we'll have to do a cleanup at some point. Unfortunately that'll be a tough job because it's sometimes hard to tell whether a key is used anywhere. The problem will be worse for OJS 3.0 than it is for OMP; I'm hoping to write a tool to help with this before the OJS 3.0 release.

**Comment by ankosi** [comment]
Hi @asmecher. Oh, I see, this is a major task. I close this issue, since I guess you have it already on a to-do-list.
