### ISSUE TITLE
Weird error report in submission process

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp#40]
When the author uploads a file in submission and forgets to insert the metadate (file name) for the second language, he gets a strange looking error message:
![2015-11-19-greenshot-incomplete_metadata_in_file_uploading_process](https://cloud.githubusercontent.com/assets/11088169/11266339/292a1fc8-8ea4-11e5-88d9-ce437c139f35.png)

**Comment by asmecher** [comment]
@withanage, just checking -- did you mean to assign this to yourself? If not, let me know and I can take a look.

**Comment by withanage** [comment]
@asmecher  - Sorry, I assigned myself to  reproduce the problem and confirm.  Please have a look.
You can reproduce this problem only if you are in  a second language.  If you change the language to english this does not occur. 

The full log is included as attachment.
[issue40.txt](https://github.com/UB-Heidelberg/omp/files/55141/issue40.txt)

**Comment by asmecher** [comment]
This should be fixed by the attached commit.

**Comment by kadowa** [comment]
@AnjaKonopka, can you check on occasion, if the problem is fixed and close the issue in that case?

**Comment by ankosi** [comment]
Bug is fixed, thanks!
