### ISSUE TITLE
Missing Search Form in Settings > Users & Roles > User Management

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#41]
In OMP 1.1.1.0 it is possible to add a user that was created in a different context using a search form on the User Management Settings page:

![users_old](https://cloud.githubusercontent.com/assets/8066366/11560588/dc32e8de-99c1-11e5-81a7-9a09ad833018.png)

Now this search form is gone:

![users_new](https://cloud.githubusercontent.com/assets/8066366/11560589/dd692240-99c1-11e5-830d-f8aff179e967.png)

Has this functionality moved to a different place?

**Comment by withanage** [comment]
when you click the magnify button near add user, the old bar   appears.

**Comment by kadowa** [comment]
Of course, thanks! Guck mal, @alleste. :grinning: :eyeglasses:

**Comment by ghost** [comment]
Oh! Und das trotz Brille ...
