### ISSUE TITLE
"Press Manager" löschen nach dem Upload

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/omp#42]
Hallo @kadowa,

es steht das nächste Problem an: Wenn man als "Press Manager" einen Titel hochgeladen und veröffentlicht hat, kann man zwar problemlos noch einen Autor hinzu fügen, der Press Manager bleibt aber ebenfalls bestehen. Gibt es eine Möglichkeit, den Press Manager zu löschen oder wenigstens aus der Anzeige zu nehmen?

![omp_press manager](https://cloud.githubusercontent.com/assets/15866252/11834085/5b427534-a3c9-11e5-9c09-e03725f8844c.jpg)
![omp-autor](https://cloud.githubusercontent.com/assets/15866252/11834087/5e851d6e-a3c9-11e5-8d35-7ce40a6ba33b.jpg)

Viele Grüße
Daniela 
i.A. Katrin Bemmann ;-)

**Comment by kadowa** [comment]
@danielawolf, durch das letzte Update gestern sind die kleinen Pfeile, hinter denen sich in der Liste der Beitragenden das Löschen-Feld verbirgt, kurzzeitig verloren gegangen (s. auch https://github.com/UB-Heidelberg/omp/issues/18#issuecomment-164807115). Jetzt sollten sie wieder da sein.

Allerdings wird beim Löschen eines Autors immer noch eine Fehlermeldung angezeigt – das hatten wir schon in #28 dokumentiert. Der Autor wird aber trotz der Fehlermeldung gelöscht, also am besten einfach die Anzeige ignorieren, bis das Problem behoben ist. :smirk:

**Comment by dastewo** [comment]
@kadowa 
Danke dir :-) Frau Bemmann testet, aber ich denke, damit sollte das Problem behoben sein.

Viele Grüße
Daniela

**Comment by dastewo** [comment]
@kadowa 
Leider tauchen diese Pfeile bei Frau Bemmann nicht auf. Der Titel ist ja bereits veröffentlicht und befindet sich nicht mehr in der Einreichungsphase. Da geht das anscheinend nicht.

Viele Grüße
Daniela

**Comment by kadowa** [comment]
Ich glaube nicht, dass es daran lieg; ich kann in meiner lokalen Testinstanz auch bei bereits veröffentlichten Katalogeinträge die Autorenliste editieren. Ich forsche mal weiter ...

**Comment by kadowa** [comment]
Neue Autoren hinzuzufügen geht schon mal:
![autoren](https://cloud.githubusercontent.com/assets/8066366/11838446/666c920a-a3e7-11e5-8e35-cbaa5740f16e.png)

**Comment by dastewo** [comment]
Ja, das hat Frau Bemmann auch schon festgestellt. Aber das löschen geht 
eben nicht mehr.

Am 16.12.2015 um 11:23 schrieb kadowa:

> Neue Autoren hinzuzufügen geht schon mal:
> autoren 
> https://cloud.githubusercontent.com/assets/8066366/11838446/666c920a-a3e7-11e5-8e35-cbaa5740f16e.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/omp/issues/42#issuecomment-165058122.

## 

---

Daniela Wolf
Webteam / Campus-Bibliothek Bergheim (CBB)
Universitaetsbibliothek Heidelberg
Ploeck 107-109, D-69117 Heidelberg
Phone: +49 6221 54 2389
Fax:   +49 6221 54 2623
Mail:  Wolf_Daniela@ub.uni-heidelberg.de

---

**Comment by kadowa** [comment]
Ich bin mir sicher, dass das Löschen funktioniert, nur die Anzeige des Löschbuttons nicht – daher der Test mit dem Anlegen. Bin dran, aber Debugging in PHP ist eine relativ unschöne Angelegenheit und dauert.

**Comment by dastewo** [comment]
Kein Problem :-)

Am 16.12.2015 um 11:29 schrieb kadowa:

> Ich bin mir sicher, dass das Löschen funktioniert, nur die Anzeige des 
> Löschbuttons nicht – daher der Test mit dem Anlegen. Bin dran, aber 
> Debugging in PHP ist eine relativ unschöne Angelegenheit und dauert.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/omp/issues/42#issuecomment-165059320.

## 

---

Daniela Wolf
Webteam / Campus-Bibliothek Bergheim (CBB)
Universitaetsbibliothek Heidelberg
Ploeck 107-109, D-69117 Heidelberg
Phone: +49 6221 54 2389
Fax:   +49 6221 54 2623
Mail:  Wolf_Daniela@ub.uni-heidelberg.de

---

**Comment by kadowa** [comment]
Ein kurzer Zwischenstand: Es ist leider weiterhin unklar, warum die Anzeige der Lösch/Editierfunktion nicht klappt; mit der Test-Datenbank funktioniert es auf demselben Server mit demselben Code einwandfrei. Das Problem liegt also weder in OMP noch in der Server-Konfiguration, sondern an der Konfiguration der konkreten Instanz – es betrifft alle Presses, also heiup, propylaeum etc. gleichermaßen.

Mir sind mittlerweile die Ideen ausgegangen; @withanage, hast du noch eine Idee? Den Hinweis von Alec den Cache zu löschen habe ich schon ganz am Anfang probiert.

**Comment by kadowa** [comment]
Vermutlich hatten wir es mit diesem Problem zu tun: https://github.com/pkp/pkp-lib/issues/1106 Sollte jetzt behoben sein. @danielawolf, kannst du das bestätigen?

**Comment by dastewo** [comment]
@kadowa Ich gebe Katrin Bescheid, dass sie testen kann.

**Comment by dastewo** [comment]
@kadowa Ich habe Katrins Bestätigung, dass es nun geht und schließe damit das Issue :-)
