### ISSUE TITLE
Feature funktioniert nicht

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/omp#43]
Hallo @kadowa,

hier gleich noch ein Problem: Das Featuren/Empfehlen der online gestellten Beiträge funktioniert nicht. Beim Klicken auf den Link "Empfehlen" passiert nichts, es gibt keine Reaktion (weder positiv noch negativ).

Viele Grüße
Daniela

**Comment by kadowa** [comment]
Kannst du mir einen Screenshot posten, damit ich weiß, wo diese Funktioalität in OMP sitzt? Was sollte denn tatsächlich passieren, wenn man auf "Empfehlen" klickt?

**Comment by dastewo** [comment]
@kadowa: hier :-)

![featuren in omp](https://cloud.githubusercontent.com/assets/15866252/11838642/9c81a5aa-a3e8-11e5-8bf9-a24293492dff.jpg)

**Comment by kadowa** [comment]
Und was sollte dieser Link tun? Das wäre sehr hilfreich, um herauszufinden, warum er es nicht tut. :wink:

**Comment by kadowa** [comment]
Anders gefragt: Was ist in der alten OMP passiert, wenn man auf diese Anzeigeoption (das ist der Sinn dahinter, oder?) umgeschaltet hat?

**Comment by dastewo** [comment]
Dann konnte man die Reihenfolge der Titel beliebig ändern. Gerade bei 
Retrodigitalisaten ist es nicht unbedingt gewollt, dass sie ganz vorne 
stehen, auch wenn sie als letztes hochgeladen wurden.

Am 16.12.2015 um 11:38 schrieb kadowa:

> Anders gefragt: Was ist in der alten OMP passiert, wenn man auf diese 
> Anzeigeoption (das ist der Sinn dahinter, oder?) umgeschaltet hat?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/omp/issues/43#issuecomment-165061380.

## 

---

Daniela Wolf
Webteam / Campus-Bibliothek Bergheim (CBB)
Universitaetsbibliothek Heidelberg
Ploeck 107-109, D-69117 Heidelberg
Phone: +49 6221 54 2389
        +49 6221 54 6683
Fax:   +49 6221 54 2623
Mail:  Wolf_Daniela@ub.uni-heidelberg.de

---

**Comment by kadowa** [comment]
Ok, danke für die Erklärung. Das sollten wir an PKP weiterreichen. @danielawolf, könntest du das Issue noch mal auf Englisch formulieren?

**Comment by dastewo** [comment]
@asmecher
We have a problem with the feature function in the new OMP version. We click on the link 'feature', but nothing happens. There is no reaction if this works or if there is an error. Could you please check this out?

Kind regards
Daniela

**Comment by asmecher** [comment]
@NateWr was working on some related stuff -- Nate, how far towards the "manage catalog" interface pictured above did you get?

**Comment by NateWr** [comment]
@asmecher I haven't touched it yet. Still a mess! Logged an [issue](https://github.com/pkp/pkp-lib/issues/986) against the OMP 1.2 milestone.

**Comment by asmecher** [comment]
@danielawolf and @withanage, I think this can be closed in favour of the issue in our repo:
https://github.com/pkp/pkp-lib/issues/986

**Comment by dastewo** [comment]
@kadowa, @withanage 
Habt ihr denn Zugriff auf https://github.com/pkp/pkp-lib/issues/986 ? Wenn nicht, würde ich das Issue hier lieber offen lassen, damit man es im Auge hat.

**Comment by kadowa** [comment]
@danielawolf, grundsätzlich kann jeder von uns auch PKP-Issues kommentieren. Mit der _Subscribe_-Funktion kannst du alle Nachrichten zum Issue abonnieren.

![subscribe](https://cloud.githubusercontent.com/assets/8066366/12289233/a1d924b2-b9da-11e5-8ddc-d42e7aea8a7e.png)

Reicht das, um es im Auge zu behalten?

**Comment by withanage** [comment]
@danielawolf  ,  bitte auf 
https://github.com/pkp/pkp-lib/issues/986
abonieren.
