### ISSUE TITLE
Kurze Terminanfrage

### ISSUE THREAD

**Issue by lmaylein** [UB-Heidelberg/omp#46]
Hallo Dulip,
am 14.03. oder 15.03. würde Herr Montero (data2type) mit jemand aus Wien bezüglich
OJS bei uns vorbeikommen. Hast Du an beiden Terminen Zeit?
Leo

**Comment by withanage** [comment]
hallo Leo,
bei mir sind die beide Tage noch  frei. Habe vorläufig gesperrt.
VG,
Dulip
