### ISSUE TITLE
Neuen arthistoricum-OMP-Link in OMP-Wiki eintragen

### ISSUE THREAD

**Issue by bettinamueller** [UB-Heidelberg/omp#55]
Liebe Wiki-Kollegen,
es gibt einen neuen Link zur arthistoricum-OMP-Bearbeitungsseite. Dieser sollte in unser UB-Wiki eingetragen werden.

Liebe Grüße,
Eure Bettina
@withanage @kadowa @AnjaKonopka @fkrb

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/omp-1.1.1.0#3
