### ISSUE TITLE
OAI interface not functional in vanilla OMP 1.2: PublicationFormat::setSeq() missing?

### ISSUE THREAD

**Issue by UmbrellaDish** [UB-Heidelberg/omp#57]
Hi,

I installed my own plain vanilla OMP instance from the official repository in my endeavour to track down an error why the OAI interface does not work on presses when they are enabled (otherwise it still seems to work only for parts of a series - few monographs we publish are that), and if it that bug is upstream or caused by changes we did.

As installation of lib/pkp submodule and composing in all those dependencies would require to deactivate the firewall (in my eyes an precarious thing to work around by all means), I just `cp -a`d it from our functional main testing instance, presuming my coworkers haven't touched a thing in that area.

Indeed, the OAI interface is defect, but in contrary to the original error which I want to pin down and which does not get logged, the following message is logged so I guess my installation is just a little different or lacking some thing:

```
    [Thu Aug 11 17:25:15.857262 2016] [:error] [pid 4709] [client ...:51312] PHP Fatal error:  Call to undefined method PublicationFormat::setSeq() in /.../classes/publicationFormat/PublicationFormatDAO.inc.php on line 152
```

However I wonder that, with `grep` I could not discover any difference in the source code compared to our main testing instance.

Hope you can shade some light on what may be wrong, sorry PHP is not my "mother tongue" in programing, so the problem might be trivial.

UmbrellaDish

**Comment by UmbrellaDish** [comment]
Solved. In lib/pkp there have been renamings of various getSeq -> getSequence recently and the OAI interface apparently is not yet in sync in my test directory.

**Comment by withanage** [comment]
Are there any remaining issues or can  we close the ticket ?

**Comment by UmbrellaDish** [comment]
There are still issues:

```
   [Mon Aug 22 09:45:24.105709 2016] [:error] [pid 30477] [client ...:55080] PHP Fatal error:  Call to undefined method PublishedMonograph::getCoverageGeo() in .../plugins/metadata/dc11/filter/Dc11SchemaPublicationFormatAdapter.inc.php on line 171
```

Apparently there is no way around proper installation of lib/pkp submodule with PHP composer, which actually means to deactivate the software firewall and to reactivate it afterwards. Let's see if it works ... for now, you can close this issue.
