### ISSUE TITLE
switch to backoffice - don't call it "dashboard"?

### ISSUE THREAD

**Issue by CFanselow** [UB-Heidelberg/omp#6]
![switchtobackoffice](https://cloud.githubusercontent.com/assets/7779279/10732007/5a731ed6-7bf8-11e5-95c4-8fa484beb7a9.png)

I wouldn't call the switch "dashboard" because there's more behind it than just the dashboard. Maybe "backoffice" or something like this.

**Comment by asmecher** [comment]
@CFanselow, there's some existing discussion of this at https://github.com/pkp/pkp-lib/issues/941 -- I'd suggest closing this issue and discussing the rename over there.
