### ISSUE TITLE
DOI (and other) plugin settings are missing

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/omp#8]
Plugin settings don't show up for the DOI plugin (and the URN DNB plugin, which works in a similar way).

![no_plugin_settings](https://cloud.githubusercontent.com/assets/8066366/10756593/53aab3ea-7ca5-11e5-9fd7-9dcee9ec3923.png)

For some of the generic plugins, management options do show up, but don't work (Translator, Usage Statistics). Custom Block Manager and Static Pages management both works, as far as I can tell.

I guess this issue is due to these changes: https://github.com/pkp/pkp-lib/commit/e678078cf1717bd9785b446f84037eeda969fa9d

**Comment by withanage** [comment]
new issue generated: https://github.com/UB-Heidelberg/omp/issues/22
