### ISSUE TITLE
Log-in + Tabs

### ISSUE THREAD

**Issue by bozana** [UB-Heidelberg/omp#9]
If using tab: on the second tab, the user will be on "Forgot your password?". Maybe to put it after the password input field, in order to quicker log-in? But maybe it's just me, used to it... :-)

**Comment by asmecher** [comment]
I think @NateWr already has this filed somewhere, but I couldn't find it.

**Comment by NateWr** [comment]
It's logged in the big [Frontend Issues](https://github.com/pkp/pkp-lib/issues/639) ticket.

**Comment by asmecher** [comment]
Thanks, @NateWr. @bozana, can you close this issue, since it's a duplicate?
